class Serial:
    def __init__(self, port: str, baudrate: int, timeout: float = ...) -> None: ...
    def __enter__(self) -> Serial: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> bool | None: ...
    def readline(self) -> bytes: ...
